format_macro_matchers = true
format_macro_bodies = true

format_strings = true

match_block_trailing_comma = true

merge_derives = true

imports_granularity = "Crate"

newline_style = "Unix"

normalize_comments = true
wrap_comments = true

reorder_impl_items = true

use_field_init_shorthand = true
