[package]
name = "rust-cuda-derive"
version = "0.1.0"
authors = ["Momo Langenstein <momo.langenstein@helsinki.fi>"]
license = "MIT OR Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
proc-macro-error = "1.0"
regex = "1.5"
lazy_static = "1.4"
serde_json = "1.0"
cargo_metadata = { version = "0.14", features = ["builder"] }
strip-ansi-escapes = "0.1"
colored = "2.0"

seahash = "4.1"
ptx-builder = { git = "https://github.com/MomoLangenstein/rust-ptx-builder", rev = "65e8f21" }
